STAR_OUTPUT_DIR = 'STAR'
STAR_SOLO_DIR = 'Solo.out'
STAR_GENE_DIR = 'Gene'
STAR_RAW_DIR = 'raw'
STAR_FILTERED_DIR = 'filtered'
STAR_VELOCYTO_DIR = 'Velocyto'
STAR_BAM_FILENAME = 'Aligned.sortedByCoord.out.bam'
STAR_BAI_FILENAME = 'Aligned.sortedByCoord.out.bai'
STAR_BARCODES_FILENAME = 'barcodes.tsv'
STAR_FEATURES_FILENAME = 'features.tsv'
STAR_MATRIX_FILENAME = 'matrix.mtx'

CONVERSIONS_FILENAME = 'conversions.csv'
CONVERSIONS_INDEX_FILENAME = 'conversions.idx'
NO_CONVERSIONS_FILENAME = 'no_conversions.csv'

SNP_DIR = 'snp'
COVERAGE_FILENAME = 'coverage.csv'
COVERAGE_INDEX_FILENAME = 'coverage.idx'
SNPS_FILENAME = 'snps.csv'

COUNT_FILENAME = 'counts.csv'
BARCODES_FILENAME = 'barcodes.csv'
GENES_FILENAME = 'genes.csv'
RATES_FILENAME = 'rates.csv'

AGGREGATES_DIR = 'aggregates'

ESTIMATES_DIR = 'estimates'
P_E_FILENAME = 'p_e.csv'
P_C_FILENAME = 'p_c.csv'
AGGREGATE_FILENAME = 'aggregate.csv'
PI_FILENAME = 'pi.csv'

ADATA_FILENAME = 'adata.h5ad'
