STAR_OUTPUT_DIR = 'STAR'
STAR_SOLO_DIR = 'Solo.out'
STAR_GENE_DIR = 'Gene'
STAR_RAW_DIR = 'raw'
STAR_FILTERED_DIR = 'filtered'
STAR_VELOCYTO_DIR = 'Velocyto'
STAR_BAM_FILENAME = 'Aligned.sortedByCoord.out.bam'
STAR_BAI_FILENAME = 'Aligned.sortedByCoord.out.bai'
STAR_BARCODES_FILENAME = 'barcodes.tsv'
STAR_FEATURES_FILENAME = 'features.tsv'
STAR_MATRIX_FILENAME = 'matrix.mtx'

INFO_FILENAME = 'info.csv'
CONVERSIONS_FILENAME = 'conversions.csv'
COVERAGE_FILENAME = 'coverage.csv'
